spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_springbootdb
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true



# Hibernate’in ddl-auto özelliği tablo yönetimi sağlar:
# create → tablolara sıfırdan başlar, eski verileri siler.
# update → tabloyu mevcut şemaya göre günceller, veri korunur.
# validate → tabloyu kontrol eder, değişiklik yapmaz.
# none → tabloya dokunmaz, Hibernate sadece sorguları çalıştırır.
